### ISSUE TITLE
module 'plaid' has no attribute 'errors'

### ISSUE THREAD

**Issue by agrieco** [mbafford/plaid-sync#4]
I'm trying to get plaid-sync working and am just getting started.  I'm finding the following errors when trying to run it for the first time.  Anyone have similar experiences and know of a fix?

thanks

```
~/plaid/plaid-sync$ ./plaid-sync.py
Traceback (most recent call last):
  File "./plaid-sync.py", line 10, in <module>
    import plaidapi
  File "/home/agrieco/plaid/plaid-sync/plaidapi.py", line 59, in <module>
    def raise_plaid(ex: plaid.errors.ItemError):
AttributeError: module 'plaid' has no attribute 'errors'
```

**Comment by agrieco** [comment]
Old python-plaid library installed.  New version fixed this issue.

**Comment by mbafford** [comment]
Apologies for the late response - I didn't get any email notification about this issue.

Did you resolve this issue? 

It seems like this might an issue of installing the wrong version of `plaid-python` - the requirements.txt asks for `7.1.0`, but the latest is `9.7.0`.

**With 9.7.0 - same error:**

```
$ .env/bin/pip install plaid-python --upgrade >&/dev/null 
$ .env/bin/pip freeze | grep plaid                       
plaid-python==9.7.0
$ env/bin/python3 -c 'import plaid; print(plaid.errors)' 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'plaid' has no attribute 'errors'
```

**With 7.1.0 - no error:**

```
$ .env/bin/pip install plaid-python==7.1.0 >&/dev/null
$ .env/bin/pip freeze | grep plaid                       
plaid-python==7.1.0
$ .env/bin/python3 -c 'import plaid; print(plaid.errors)'
<module 'plaid.errors' from '/private/tmp/plaid/.env/lib/python3.9/site-packages/plaid/errors.py'>
```

So please check which version of `plaid-python` you have installed and re-open this issue if this isn't the issue.
